export let rsc = {
  handleSubmit: "handleSubmit",
  isLoading: "isLoading",
  isSubmitting: "isSubmitting",
  initialData: "initialData",
  result: "result",
  id: "id",
  navigate: "navigate",
  useNavigate: "useNavigate",
  useParams: "useParams",
  useForm: "useForm",
  methods: "methods",
  reset: "reset",
  onSubmit: "onSubmit",
  SubmitHandler: "SubmitHandler",
  submitHandler: "submitHandler",
  dataToShow: "dataToShow",
  page: "page",
  setPage: "setPage",
  rowsPerPage: "rowsPerPage",
  setRowsPerPage: "setRowsPerPage",
  setSortBy: "setSortBy",
  usePaginableSortedData: "usePaginableSortedData",
  tableLabels: "tableLabels",
  EnqueueMessage: "EnqueueMessage",
  NotificationAdapterInvoke: "NotificationAdapter()",
  queryClient: "queryClient",
  useQueryClient: "useQueryClient",
  useDefaultRQConfig: "useDefaultRQConfig",
  config: "config",
  enabled: "enabled",
  onSuccess: "onSuccess",
  error: "error",
  mutateAsync: "mutateAsync",
  useMutation: "useMutation",
  useQuery: "useQuery",
  response: "response",
  invalidateQueries: "invalidateQueries",
  errorMessage: "errorMessage",
  getServerErrorMessage: "getServerErrorMessage",
  data: "data",
  detailsRoute: "details",
  updateRoute: "update",
  createRoute: "create",
  indexRoute: "index",
  axios: "axios",
  axiosInstance: "axiosInstance",
  axiosPost: "post",
  axiosGet: "get",
  axiosPut: "put",
  axiosDelete: "delete",
  patch: "patch",
  baseUrl: "baseUrl",
  requestDTO: "requestDTO",
  reactComponentExtension: ".tsx",
  defaultFileExtension: ".ts",
};

export const overrideRSC = (overrideDict: { [key: string]: string }) => {
  rsc = { ...rsc, ...overrideDict };
};
